language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc-4.8.1
      script:
        - git submodule update --init --recursive
        - mkdir ext/glfw/include/GL
        - wget --no-check-certificate -P ext/glfw/include/GL https://www.opengl.org/registry/api/GL/glcorearb.h
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_C_COMPILER=gcc-4.8 ../
        - make -j 2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - g++-4.8
            - cmake
            - cmake-data
           # - libblas-dev
           # - liblapack-dev
           #  - binutils
           #  - libx11-dev
           #  - mesa-common-dev
           #  - libgl1-mesa-dev
           #  - libglu1-mesa-dev
           #  - libxrandr-dev
           #  - libxi-dev
           #  - libxmu-dev
           #  - libblas-dev
           #  - xorg-dev
    - os: osx
      compiler: clang
      script:
        - git submodule update --init --recursive
        - mkdir build
        - cd build
        - cmake ../
        - make -j 2
